# Generated by Django 5.2.8 on 2025-11-19 19:15

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('WALLET', 'WALLET'), ('BTC', 'BTC'), ('ETH', 'ETH'), ('CASH APP', 'CASH APP'), ('PAYPAL', 'PAYPAL')], max_length=400)),
                ('payment_address', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(blank=True, max_length=400)),
                ('wallet_address', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name': 'Admin Wallet',
                'verbose_name_plural': 'Admin Wallets',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Universal Plan', max_length=100)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Minimum Deposit')),
                ('maximum_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Maximum Deposit')),
                ('term_duration', models.CharField(default='10 Days', max_length=100)),
                ('payout_term', models.CharField(default='Term Basis', max_length=100)),
                ('capital_return', models.CharField(default='End of Term', max_length=100)),
                ('percentage_return', models.CharField(default='130%', max_length=100)),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('preferred_currency', models.CharField(blank=True, default='$', max_length=100, null=True)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100, null=True)),
                ('user_password_in_text', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Annual Income')),
                ('citizenship_status', models.CharField(choices=[('US Citizen', 'US Citizen'), ('Non-US Citizen', 'Non-US Citizen')], default='Non-US Citizen', max_length=50)),
                ('capital', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Capital')),
                ('roi', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ROI')),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Bonus')),
                ('investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Investment')),
                ('program_type', models.CharField(blank=True, choices=[('Short-Term', 'Short-Term'), ('Long-Term', 'Long-Term')], default='Short-Term', max_length=100, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('has_verified_kyc', models.BooleanField(default=False, help_text='Tick if user has undergone KYC Verification and has been approved.', verbose_name='User is verified')),
                ('has_submitted_kyc', models.BooleanField(default=False, help_text='This means that user has submitted verification for KYC')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('WALLET', 'WALLET'), ('BTC', 'BTC'), ('ETH', 'ETH'), ('CASH APP', 'CASH APP'), ('PAYPAL', 'PAYPAL')], max_length=400)),
                ('payment_address', models.CharField(blank=True, max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Payment Information',
                'verbose_name_plural': 'Customer Payment Information',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('investment_type', models.CharField(blank=True, choices=[('Basic Plan', 'Basic Plan'), ('Standard Plan', 'Standard Plan'), ('Premium Plan', 'Premium Plan'), ('Elite Plan', 'Elite Plan')], max_length=400, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Successful', 'Successful')], default='Pending', max_length=400)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_dependents', models.IntegerField(default=0)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship_status', models.CharField(blank=True, max_length=100, null=True)),
                ('ssn', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_identity_number', models.CharField(blank=True, max_length=100, null=True)),
                ('government_id_type', models.CharField(blank=True, max_length=100, null=True)),
                ('government_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('proof_of_employment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('proof_of_income', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('front_id_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('back_id_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('image_holding_id', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('danger', 'danger'), ('success', 'success'), ('warning', 'warning')], help_text='Select the Notification Type. ', max_length=100, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifications',
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('FUNDING', 'FUNDING'), ('WITHDRAWAL', 'WITHDRAWAL')], max_length=400)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('confirmation_receipt', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=400, null=True)),
                ('wallet', models.CharField(blank=True, max_length=400, null=True)),
                ('withdraw_source', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=400)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Support',
            },
        ),
    ]
