# Generated by Django 6.0.1 on 2026-02-19 01:14

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('FUNDING', 'FUNDING'), ('WITHDRAWAL', 'WITHDRAWAL')], max_length=400)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('confirmation_receipt', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=400, null=True)),
                ('wallet', models.CharField(blank=True, max_length=400, null=True)),
                ('withdraw_source', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=400)),
                ('withdrawal_type', models.CharField(blank=True, choices=[('BANK_WIRE', 'Bank Wire Transfer'), ('CRYPTO', 'Cryptocurrency')], max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('crypto_address', models.CharField(blank=True, max_length=500, null=True)),
                ('crypto_type', models.CharField(blank=True, choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('USDT', 'Tether (USDT)'), ('USDC', 'USD Coin (USDC)'), ('BNB', 'BNB (BNB)'), ('SOL', 'Solana (SOL)'), ('XRP', 'Ripple (XRP)'), ('LTC', 'Litecoin (LTC)'), ('DOGE', 'Dogecoin (DOGE)'), ('TRX', 'TRON (TRX)')], max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
